name: Build APK and Release
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Flutter Cache
        id: flutter-cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --obfuscate --split-debug-info=/tmp --split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: ./build/app/outputs/flutter-apk/
          retention-days: 1

  release:
    needs: build
    name: Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: All of these APK files are built automatically using Github Action and not signed. Install it with your own risk!

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: apk-build
          path: /tmp

      - name: Setup Version
        id: setup-version
        run: echo "::set-output name=ver::$(echo ${{ github.ref }} | cut -d 'v' -f2)"

      - name: Upload ARM APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/app-armeabi-v7a-release.apk
          asset_name: com.gagahpangeran.readlist-arm-v${{ steps.setup-version.outputs.ver }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload ARM64 APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/app-arm64-v8a-release.apk
          asset_name: com.gagahpangeran.readlist-arm64-v${{ steps.setup-version.outputs.ver }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload X86_64 APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/app-x86_64-release.apk
          asset_name: com.gagahpangeran.readlist-x86_64-v${{ steps.setup-version.outputs.ver }}.apk
          asset_content_type: application/vnd.android.package-archive
